import { useEffect, useMemo, useState } from "react";
import { Banknote, CheckCircle2, ClockAlert, MessageCircle, Pencil, Search, WalletCards } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState, ErrorBanner, Field, Loading, Modal, PageHeader } from "../components/ui";
import { api, money, shortDate } from "../lib/api";
import type { Payment } from "../types";

const paymentLabels: Record<string, string> = { pendente: "Pendente", parcial: "Parcial", pago: "Pago", vencido: "Vencido", cancelado: "Cancelado", estornado: "Estornado" };

export function FinancePage() {
  const [payments, setPayments] = useState<Payment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [tab, setTab] = useState("abertos"); const [editing, setEditing] = useState<Payment | null>(null);
  async function load() { try { setPayments(await api<Payment[]>("/payments")); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao carregar pagamentos."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const open = payments.filter((p) => ["pendente", "parcial", "vencido"].includes(p.status));
  const visible = useMemo(() => payments.filter((payment) => (tab === "todos" || (tab === "abertos" ? ["pendente", "parcial", "vencido"].includes(payment.status) : payment.status === tab)) && `${payment.orderNumber} ${payment.customerName}`.toLowerCase().includes(search.toLowerCase())), [payments, tab, search]);
  const balance = (payment: Payment) => Math.max(0, Number(payment.amount) - Number(payment.receivedAmount));
  const pendingTotal = open.reduce((sum, p) => sum + balance(p), 0); const overdue = open.filter((p) => p.dueDate && p.dueDate < new Date().toISOString().slice(0, 10));
  async function markPaid(payment: Payment) { try { await api(`/payments/${payment.id}`, { method: "PATCH", body: JSON.stringify({ status: "pago" }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao confirmar pagamento."); } }
  async function contact(payment: Payment) { const notes = prompt("Registre o resultado do contato de cobrança:"); if (!notes) return; const channel = prompt("Canal utilizado (WhatsApp, telefone ou e-mail):", "WhatsApp") || "WhatsApp"; try { await api(`/payments/${payment.id}/contacts`, { method: "POST", body: JSON.stringify({ channel, notes }) }); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao registrar contato."); } }
  return <><PageHeader eyebrow="Contas a receber" title="Financeiro" description="Acompanhe vencimentos, cobranças e confirmações de pagamento." />{error && <ErrorBanner message={error} />}
    <section className="finance-metrics"><article><span><WalletCards /></span><div><small>Total em aberto</small><strong>{money(pendingTotal)}</strong><em>{open.length} cobranças</em></div></article><article><span className="danger"><ClockAlert /></span><div><small>Vencidos</small><strong>{money(overdue.reduce((sum, p) => sum + balance(p), 0))}</strong><em>{overdue.length} cobranças</em></div></article><article><span className="success"><CheckCircle2 /></span><div><small>Recebidos</small><strong>{money(payments.reduce((sum, p) => sum + Number(p.receivedAmount), 0))}</strong><em>na base atual</em></div></article></section>
    <div className="tabs"><button className={tab === "abertos" ? "active" : ""} onClick={() => setTab("abertos")}>Em aberto</button><button className={tab === "pago" ? "active" : ""} onClick={() => setTab("pago")}>Pagos</button><button className={tab === "todos" ? "active" : ""} onClick={() => setTab("todos")}>Todos</button></div>
    <div className="toolbar"><div className="search-box"><Search size={17} /><input placeholder="Buscar pedido ou cliente..." value={search} onChange={(e) => setSearch(e.target.value)} /></div></div>
    {loading ? <Loading /> : visible.length ? <div className="data-table finance-table"><div className="data-head"><span>Pedido / cliente</span><span>Vencimento</span><span>Forma</span><span>Valor / saldo</span><span>Situação</span><span>Ações</span></div>{visible.map((payment) => { const isOverdue = !!payment.dueDate && payment.dueDate < new Date().toISOString().slice(0, 10) && payment.status !== "pago"; return <div className="data-row" key={payment.id}><div><Link to={`/pedidos/${payment.orderId}`}><strong>{payment.orderNumber}</strong></Link><small>{payment.customerName}</small></div><span className={isOverdue ? "danger-text" : ""}>{shortDate(payment.dueDate)}</span><span className="capitalize">{payment.method}</span><div><strong>{money(payment.amount)}</strong><small>saldo {money(balance(payment))}</small></div><span><i className={`payment-status payment-${isOverdue ? "vencido" : payment.status}`}>{isOverdue ? "Vencido" : paymentLabels[payment.status]}</i></span><div className="row-actions"><button className="icon-button" onClick={() => setEditing(payment)} title="Editar pagamento"><Pencil size={16} /></button>{payment.status !== "pago" && <><button className="icon-button" onClick={() => void contact(payment)} title="Registrar cobrança"><MessageCircle size={17} /></button><button className="button primary small" onClick={() => void markPaid(payment)}><CheckCircle2 size={15} /> Confirmar</button></>}</div></div>; })}</div> : <EmptyState icon={<Banknote />} title="Nenhuma cobrança" description="Não há pagamentos neste filtro." />}
    <PaymentModal payment={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void load(); }} />
  </>;
}

function PaymentModal({ payment, onClose, onSaved }: { payment: Payment | null; onClose: () => void; onSaved: () => void }) {
  const [status, setStatus] = useState<Payment["status"]>("pendente"); const [receivedAmount, setReceivedAmount] = useState(0); const [method, setMethod] = useState(""); const [dueDate, setDueDate] = useState(""); const [proofReference, setProofReference] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (payment) { setStatus(payment.status); setReceivedAmount(Number(payment.receivedAmount)); setMethod(payment.method); setDueDate(payment.dueDate ?? ""); setProofReference(payment.proofReference ?? ""); setNotes(payment.notes ?? ""); setError(""); } }, [payment]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!payment) return; setSaving(true); setError(""); try { await api(`/payments/${payment.id}`, { method: "PATCH", body: JSON.stringify({ status, receivedAmount: status === "parcial" ? receivedAmount : undefined, method, dueDate: dueDate || null, proofReference: proofReference || null, notes: notes || null }) }); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao atualizar pagamento."); } finally { setSaving(false); } }
  return <Modal open={!!payment} title="Atualizar pagamento" onClose={onClose}><form className="modal-body" onSubmit={submit}>{error && <ErrorBanner message={error} />}<div className="form-grid two"><Field label="Situação"><select value={status} onChange={(e) => setStatus(e.target.value as Payment["status"])}>{Object.entries(paymentLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Forma"><input value={method} onChange={(e) => setMethod(e.target.value)} required /></Field><Field label="Vencimento"><input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></Field>{status === "parcial" && <Field label="Valor recebido"><input type="number" min="0.01" max={payment ? Math.max(Number(payment.amount) - 0.01, 0.01) : undefined} step="0.01" value={receivedAmount} onChange={(e) => setReceivedAmount(Number(e.target.value))} required /></Field>}</div><Field label="Comprovante / referência"><input value={proofReference} onChange={(e) => setProofReference(e.target.value)} /></Field><Field label="Observações"><textarea rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} /></Field><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" disabled={saving}>{saving ? "Salvando..." : "Salvar"}</button></div></form></Modal>;
}
