import { useEffect, useMemo, useState } from "react";
import { Factory, Filter, Play, Search, Square, TimerReset } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState, ErrorBanner, Loading, PageHeader, PriorityBadge } from "../components/ui";
import { api, shortDate } from "../lib/api";
import type { ProductionJob } from "../types";

export function ProductionPage() {
  const [jobs, setJobs] = useState<ProductionJob[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("todos");
  async function load() { try { setJobs(await api<ProductionJob[]>("/production")); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao carregar produção."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const rows = useMemo(() => jobs.filter((job) => (filter === "todos" || job.status === filter) && `${job.orderNumber} ${job.customerName}`.toLowerCase().includes(search.toLowerCase())), [jobs, filter, search]);
  async function update(job: ProductionJob, status: string) { try { await api(`/production/${job.id}`, { method: "PATCH", body: JSON.stringify({ status }) }); if (status === "em_andamento" && job.orderStatus === "pagamento_confirmado") await api(`/orders/${job.orderId}/transition`, { method: "POST", body: JSON.stringify({ status: "em_producao" }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao atualizar produção."); } }
  return <><PageHeader eyebrow="Fila de trabalho" title="Produção" description="Priorize os pedidos, registre início e conclusão do trabalho." />{error && <ErrorBanner message={error} />}<div className="toolbar"><div className="search-box"><Search size={17} /><input placeholder="Buscar pedido ou cliente..." value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="filter-select"><Filter size={16} /><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="todos">Todos</option><option value="aguardando">Aguardando</option><option value="em_andamento">Em andamento</option><option value="pausado">Pausado</option><option value="concluido">Concluído</option></select></div></div>
    {loading ? <Loading /> : rows.length ? <div className="work-list">{rows.map((job) => <article className="work-card" key={job.id}><div className={`work-status status-work-${job.status}`}><Factory /><span>{job.status.replaceAll("_", " ")}</span></div><div className="work-order"><Link to={`/pedidos/${job.orderId}`}><strong>{job.orderNumber}</strong></Link><h3>{job.customerName}</h3><PriorityBadge priority={job.priority} /></div><div className="work-date"><span>Data limite</span><strong>{shortDate(job.promisedDate)}</strong></div><div className="work-person"><span>Responsável</span><strong>{job.assigneeName ?? "Não atribuído"}</strong></div><div className="work-actions">{job.status !== "em_andamento" && job.status !== "concluido" && <button className="button primary small" onClick={() => void update(job, "em_andamento")}><Play size={15} /> Iniciar</button>}{job.status === "em_andamento" && <><button className="button secondary small" onClick={() => void update(job, "pausado")}><TimerReset size={15} /> Pausar</button><button className="button primary small" onClick={() => void update(job, "concluido")}><Square size={14} /> Concluir</button></>}</div></article>)}</div> : <EmptyState icon={<Factory />} title="Fila vazia" description="Não há pedidos com estes filtros." />}
  </>;
}
