import { useEffect, useState, type FormEvent } from "react";
import { Boxes, Plus, Search, Tags, UserCog, UsersRound } from "lucide-react";
import { EmptyState, ErrorBanner, Field, Loading, Modal, PageHeader } from "../components/ui";
import { useAuth } from "../contexts/AuthContext";
import { api, money } from "../lib/api";
import { roleLabel, type Category, type Customer, type Product, type Role, type User } from "../types";

type Tab = "clientes" | "produtos" | "categorias" | "usuarios";
export function RegistrationsPage() {
  const { user } = useAuth();
  const [tab, setTab] = useState<Tab>("clientes"); const [customers, setCustomers] = useState<Customer[]>([]); const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [users, setUsers] = useState<User[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [search, setSearch] = useState(""); const [error, setError] = useState("");
  const managesUsers = user?.role === "gestor" || user?.role === "administrador";
  const canAdd = tab !== "categorias" || managesUsers;
  const availableTabs: Tab[] = managesUsers ? ["clientes", "produtos", "categorias", "usuarios"] : ["clientes", "produtos", "categorias"];
  async function load() { setLoading(true); try { const [c, p, cat, u] = await Promise.all([api<Customer[]>("/customers"), api<Product[]>("/products"), api<Category[]>("/categories"), managesUsers ? api<User[]>("/users") : Promise.resolve([])]); setCustomers(c); setProducts(p); setCategories(cat); setUsers(u); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao carregar cadastros."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const counts = { clientes: customers.length, produtos: products.length, categorias: categories.length, usuarios: users.length };
  return <><PageHeader eyebrow="Base operacional" title="Cadastros" description="Mantenha clientes, catálogo e equipe sempre atualizados." actions={canAdd && <button className="button primary" onClick={() => setOpen(true)}><Plus size={18} /> Adicionar</button>} />{error && <ErrorBanner message={error} />}
    <div className="registration-tabs">{availableTabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => { setTab(item); setSearch(""); }}><span>{item === "clientes" ? <UsersRound /> : item === "produtos" ? <Boxes /> : item === "categorias" ? <Tags /> : <UserCog />}{item}</span><strong>{counts[item]}</strong></button>)}</div>
    <div className="toolbar"><div className="search-box"><Search size={17} /><input placeholder={`Buscar ${tab}...`} value={search} onChange={(e) => setSearch(e.target.value)} /></div></div>
    {loading ? <Loading /> : <RegistrationContent tab={tab} search={search} customers={customers} products={products} categories={categories} users={users} />}
    <RegistrationModal open={open} tab={tab} categories={categories} onClose={() => setOpen(false)} onCreated={() => { setOpen(false); void load(); }} />
  </>;
}

function RegistrationContent({ tab, search, customers, products, categories, users }: { tab: Tab; search: string; customers: Customer[]; products: Product[]; categories: Category[]; users: User[] }) {
  const matches = (value: string) => value.toLowerCase().includes(search.toLowerCase());
  if (tab === "clientes") { const rows = customers.filter((c) => matches(`${c.name} ${c.document ?? ""} ${c.phone ?? ""}`)); return rows.length ? <div className="cards-table">{rows.map((c) => <article key={c.id}><div className="entity-avatar">{c.name.slice(0, 2).toUpperCase()}</div><div><strong>{c.name}</strong><span>{c.document ?? "Documento não informado"}</span></div><span>{c.phone ?? "—"}</span><span>{c.email ?? "—"}</span><i className={c.active ? "active" : "inactive"}>{c.active ? "Ativo" : "Inativo"}</i></article>)}</div> : <EmptyState icon={<UsersRound />} title="Nenhum cliente" description="Adicione o primeiro cliente." />; }
  if (tab === "produtos") { const rows = products.filter((p) => matches(`${p.name} ${p.sku}`)); return rows.length ? <div className="cards-table">{rows.map((p) => <article key={p.id}><div className="entity-avatar product"><Boxes /></div><div><strong>{p.name}</strong><span>{p.sku}</span></div><span>{p.categoryName ?? "Sem categoria"}</span><strong>{money(p.price)}</strong><i className={p.active ? "active" : "inactive"}>{p.active ? "Ativo" : "Inativo"}</i></article>)}</div> : <EmptyState icon={<Boxes />} title="Nenhum produto" description="Cadastre o catálogo inicial." />; }
  if (tab === "categorias") { const rows = categories.filter((c) => matches(c.name)); return <div className="category-grid">{rows.map((c) => <article key={c.id}><Tags /><strong>{c.name}</strong><span>{products.filter((p) => p.categoryId === c.id).length} produtos</span></article>)}</div>; }
  const rows = users.filter((u) => matches(`${u.name} ${u.email}`)); return rows.length ? <div className="cards-table">{rows.map((u) => <article key={u.id}><div className="entity-avatar user">{u.name.slice(0, 2).toUpperCase()}</div><div><strong>{u.name}</strong><span>{u.email}</span></div><span>{u.department ?? "—"}</span><span>{roleLabel[u.role]}</span><i className="active">Ativo</i></article>)}</div> : <EmptyState icon={<UserCog />} title="Nenhum usuário" description="Cadastre a equipe." />;
}

function RegistrationModal({ open, tab, categories, onClose, onCreated }: { open: boolean; tab: Tab; categories: Category[]; onClose: () => void; onCreated: () => void }) {
  const [data, setData] = useState<Record<string, string>>({}); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const set = (key: string) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setData((value) => ({ ...value, [key]: event.target.value }));
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const path = tab === "clientes" ? "/customers" : tab === "produtos" ? "/products" : tab === "categorias" ? "/categories" : "/users"; const body = tab === "produtos" ? { ...data, price: Number(data.price), productionMinutes: Number(data.productionMinutes ?? 0), categoryId: data.categoryId || null } : tab === "clientes" ? { name: data.name, document: data.document, phone: data.phone, email: data.email, notes: data.notes, address: { street: data.street, number: data.number, complement: data.complement, district: data.district, city: data.city, state: data.state, zipCode: data.zipCode } } : data; await api(path, { method: "POST", body: JSON.stringify(body) }); setData({}); onCreated(); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao salvar cadastro."); } finally { setSaving(false); } }
  return <Modal open={open} title={`Novo ${tab.slice(0, -1)}`} onClose={onClose}><form className="modal-body" onSubmit={submit}>{error && <ErrorBanner message={error} />}
    {tab === "clientes" && <><Field label="Nome"><input value={data.name ?? ""} onChange={set("name")} required /></Field><div className="form-grid two"><Field label="Documento"><input value={data.document ?? ""} onChange={set("document")} /></Field><Field label="Telefone"><input value={data.phone ?? ""} onChange={set("phone")} /></Field></div><Field label="E-mail"><input type="email" value={data.email ?? ""} onChange={set("email")} /></Field><div className="form-grid two"><Field label="Rua"><input value={data.street ?? ""} onChange={set("street")} /></Field><Field label="Número"><input value={data.number ?? ""} onChange={set("number")} /></Field><Field label="Complemento"><input value={data.complement ?? ""} onChange={set("complement")} /></Field><Field label="Bairro"><input value={data.district ?? ""} onChange={set("district")} /></Field><Field label="Cidade"><input value={data.city ?? ""} onChange={set("city")} /></Field><Field label="Estado"><input maxLength={2} value={data.state ?? ""} onChange={set("state")} /></Field><Field label="CEP"><input value={data.zipCode ?? ""} onChange={set("zipCode")} /></Field></div><Field label="Observações"><input value={data.notes ?? ""} onChange={set("notes")} /></Field></>}
    {tab === "produtos" && <><div className="form-grid two"><Field label="SKU"><input value={data.sku ?? ""} onChange={set("sku")} required /></Field><Field label="Categoria"><select value={data.categoryId ?? ""} onChange={set("categoryId")}><option value="">Sem categoria</option>{categories.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></Field></div><Field label="Nome"><input value={data.name ?? ""} onChange={set("name")} required /></Field><div className="form-grid two"><Field label="Preço"><input type="number" min="0" step="0.01" value={data.price ?? ""} onChange={set("price")} required /></Field><Field label="Tempo de produção (min.)"><input type="number" min="0" value={data.productionMinutes ?? "0"} onChange={set("productionMinutes")} /></Field></div></>}
    {tab === "categorias" && <Field label="Nome"><input value={data.name ?? ""} onChange={set("name")} required /></Field>}
    {tab === "usuarios" && <><Field label="Nome"><input value={data.name ?? ""} onChange={set("name")} required /></Field><Field label="E-mail"><input type="email" value={data.email ?? ""} onChange={set("email")} required /></Field><div className="form-grid two"><Field label="Perfil"><select value={data.role ?? "atendimento"} onChange={set("role")}>{Object.entries(roleLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></Field><Field label="Área"><input value={data.department ?? ""} onChange={set("department")} /></Field></div><Field label="Senha inicial"><input type="password" minLength={8} value={data.password ?? ""} onChange={set("password")} required /></Field></>}
    <div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" disabled={saving}>{saving ? "Salvando..." : "Salvar"}</button></div>
  </form></Modal>;
}
