import { useEffect, useState, type FormEvent } from "react";
import { CheckCircle2, MapPin, Navigation, PackageOpen, Pencil, Phone, Truck } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState, ErrorBanner, Field, Loading, Modal, PageHeader, StatusBadge } from "../components/ui";
import { api, shortDate } from "../lib/api";
import type { Shipment } from "../types";

export function ShippingPage() {
  const [rows, setRows] = useState<Shipment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState<Shipment | null>(null);
  async function load() { try { setRows(await api<Shipment[]>("/shipping")); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao carregar expedição."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function move(shipment: Shipment, status: "expedicao" | "entregue") { try { await api(`/orders/${shipment.orderId}/transition`, { method: "POST", body: JSON.stringify({ status }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao atualizar entrega."); } }
  return <><PageHeader eyebrow="Saídas e entregas" title="Expedição" description="Organize retiradas, rotas e confirmações de entrega." />{error && <ErrorBanner message={error} />}
    {loading ? <Loading /> : rows.length ? <div className="shipping-board"><section><header><span><PackageOpen />Aguardando saída</span><strong>{rows.filter((r) => r.orderStatus === "pronto").length}</strong></header>{rows.filter((r) => r.orderStatus === "pronto").map((shipment) => <ShippingCard key={shipment.id} shipment={shipment} onEdit={() => setEditing(shipment)} action={<button className="button primary small" onClick={() => void move(shipment, "expedicao")}><Navigation size={15} /> Registrar saída</button>} />)}</section><section><header><span><Truck />Em rota</span><strong>{rows.filter((r) => r.orderStatus === "expedicao").length}</strong></header>{rows.filter((r) => r.orderStatus === "expedicao").map((shipment) => <ShippingCard key={shipment.id} shipment={shipment} onEdit={() => setEditing(shipment)} action={<button className="button primary small" onClick={() => void move(shipment, "entregue")}><CheckCircle2 size={15} /> Confirmar entrega</button>} />)}</section><section><header><span><CheckCircle2 />Concluídas</span><strong>{rows.filter((r) => r.orderStatus === "entregue").length}</strong></header>{rows.filter((r) => r.orderStatus === "entregue").slice(0, 8).map((shipment) => <ShippingCard key={shipment.id} shipment={shipment} onEdit={() => setEditing(shipment)} />)}</section></div> : <EmptyState icon={<Truck />} title="Sem entregas" description="Pedidos prontos e em rota aparecerão aqui." />}
    <ShipmentModal shipment={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void load(); }} />
  </>;
}

function ShippingCard({ shipment, action, onEdit }: { shipment: Shipment; action?: React.ReactNode; onEdit: () => void }) { const address = [shipment.address?.street, shipment.address?.number, shipment.address?.district, shipment.address?.city].filter(Boolean).join(", "); return <article className="shipping-card"><div><Link to={`/pedidos/${shipment.orderId}`}><strong>{shipment.orderNumber}</strong></Link><StatusBadge status={shipment.orderStatus} /></div><h3>{shipment.customerName}</h3><span><MapPin />{shipment.type === "retirada" ? "Retirada no local" : address || "Endereço não informado"}</span>{shipment.customerPhone && <span><Phone />{shipment.customerPhone}</span>}{shipment.trackingCode && <span>Rastreio: {shipment.trackingCode}</span>}{shipment.deliveryWindow && <span>Janela: {shipment.deliveryWindow}</span>}{shipment.failedReason && <span className="danger-text">Tentativa frustrada: {shipment.failedReason}</span>}<div className="shipping-meta"><span>Prazo <strong>{shortDate(shipment.promisedDate)}</strong></span><span>Responsável <strong>{shipment.driver ?? shipment.carrier ?? "A definir"}</strong></span></div><div className="shipping-actions"><button className="button secondary small" onClick={onEdit}><Pencil size={14} /> Editar</button>{action}</div></article>; }

function ShipmentModal({ shipment, onClose, onSaved }: { shipment: Shipment | null; onClose: () => void; onSaved: () => void }) {
  const [data, setData] = useState<Record<string, string>>({}); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (shipment) setData({ street: shipment.address?.street ?? "", number: shipment.address?.number ?? "", complement: shipment.address?.complement ?? "", district: shipment.address?.district ?? "", city: shipment.address?.city ?? "", state: shipment.address?.state ?? "", zipCode: shipment.address?.zipCode ?? "", deliveryWindow: shipment.deliveryWindow ?? "", carrier: shipment.carrier ?? "", driver: shipment.driver ?? "", trackingCode: shipment.trackingCode ?? "", failedReason: shipment.failedReason ?? "" }); }, [shipment]);
  const set = (key: string) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setData((current) => ({ ...current, [key]: event.target.value }));
  async function submit(event: FormEvent) { event.preventDefault(); if (!shipment) return; setSaving(true); setError(""); try { await api(`/shipping/${shipment.id}`, { method: "PATCH", body: JSON.stringify({ address: { street: data.street, number: data.number, complement: data.complement, district: data.district, city: data.city, state: data.state, zipCode: data.zipCode }, deliveryWindow: data.deliveryWindow || null, carrier: data.carrier || null, driver: data.driver || null, trackingCode: data.trackingCode || null, failedReason: data.failedReason || null }) }); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao atualizar expedição."); } finally { setSaving(false); } }
  return <Modal open={!!shipment} title="Dados da expedição" onClose={onClose} wide><form className="modal-body" onSubmit={submit}>{error && <ErrorBanner message={error} />}<div className="form-grid three"><Field label="Rua"><input value={data.street ?? ""} onChange={set("street")} /></Field><Field label="Número"><input value={data.number ?? ""} onChange={set("number")} /></Field><Field label="Complemento"><input value={data.complement ?? ""} onChange={set("complement")} /></Field><Field label="Bairro"><input value={data.district ?? ""} onChange={set("district")} /></Field><Field label="Cidade"><input value={data.city ?? ""} onChange={set("city")} /></Field><Field label="Estado"><input maxLength={2} value={data.state ?? ""} onChange={set("state")} /></Field><Field label="CEP"><input value={data.zipCode ?? ""} onChange={set("zipCode")} /></Field><Field label="Janela de entrega"><input value={data.deliveryWindow ?? ""} onChange={set("deliveryWindow")} /></Field><Field label="Transportadora"><input value={data.carrier ?? ""} onChange={set("carrier")} /></Field><Field label="Entregador"><input value={data.driver ?? ""} onChange={set("driver")} /></Field><Field label="Código de rastreio"><input value={data.trackingCode ?? ""} onChange={set("trackingCode")} /></Field></div><Field label="Motivo de tentativa frustrada"><textarea rows={3} value={data.failedReason ?? ""} onChange={set("failedReason")} /></Field><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" disabled={saving}>{saving ? "Salvando..." : "Salvar"}</button></div></form></Modal>;
}
